[package]
name = "myco"
version = "0.1.0"
authors = ["Reconcyl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.4"
rand = "0.7.2"
structopt = "0.3.5"
